tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/test-bot'
tap 'homebrew/versions'
tap 'caskroom/cask'
tap 'neovim/neovim'
tap 'crisidev/homebrew-chunkwm'
tap 'koekeishiya/formulae'
brew 'mas'
brew 'git'
brew 'node'
brew 'tmux'
brew 'zsh'
brew 'reattach-to-user-namespace'
brew 'neovim'
brew 'chunkwm', restart_service: :changed
brew 'khd', restart_service: :changed
cask 'iterm2'
cask 'google-chrome'
cask 'firefox'
