#!/bin/sh
# script/setup - Installs all dotfile dependencies after system is Bootstrapped
# Author: Evan R. Long (mail@evanrlong.com)
# Created: 2/9/17
# Updated: 2/9/17

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

echo "Installed dotfiles in home directory..."
$DOTFILESDIR/bin/dot install
