#!/bin/sh
# script/setup - Installs all dotfile dependencies after system is Bootstrapped

export DOTFILES_DIR=~/.dotfiles
[ $(uname -s) = "Darwin" ] && export MACOS=1 && export UNIX=1
[ $(uname -s) = "Linux" ] && export LINUX=1 && export UNIX=1
uname -s | grep -q "_NT-" && export WINDOWS=1

echo "Installing dotfiles in home directory..."
$DOTFILES_DIR/bin/dot install

echo "Setting default retina display scaling..."
$DOTFILES_DIR/bin/display-scaler 5

echo "Disabling Spotlight global shortcuts..."
$DOTFILES_DIR/bin/macos-shortcutter disable -a "Spotlight" -s "Show Spotlight search"
$DOTFILES_DIR/bin/macos-shortcutter disable -a "Spotlight" -s "Show Finder search window"

echo "Setup successful!  Please restart you computer to complete installation."
