#!/bin/sh
# Update dotfiles and brew bundle installs


[ -f "`which brew`" ] && export BREW=1
brew tap -1 | grep -q "^homebrew/bundle\$" && export BREWBUNDLE=1 
[ -f "$HOME/.Brewfile" ] && export BREWFILE=1

echo "Updating system dependencies with Homebrew Bundle..."
if [ $MACOS ]
then
  if [ $BREW ]
  then
    if [ $BREWBUNDLE ]
    then
      if [ $BREWFILE ]
      then
        brew bundle --global
      else
        echo "'brew bundle' could not be run because no Brewfile was found."
	echo "Create a Brewfile at ~/.Brewfile before continuing."
      fi
    else
      echo "'brew bundle' could not be run because Homebrew Bundle tap not installed."
      echo "Run 'brew tap Homebrew/bundle' before continuing."
    fi
  else
    echo "'brew bundle' could not run because Homebrew is not installed."
    echo "Follow the installation steps at http://brew.sh before continuing."
  fi
fi


echo "Updating dotfile symlinks..."
$DOTFILES_DIR/bin/dot install

echo "Installing macOS presets..."
$DOTFILES_DIR/bin/macos

echo "System successfully updated! Some updates may require a system restart to take effect."
